version: 2
enable-beta-ecosystems: true # Required while the Deno ecosystem is in beta

updates:
  - package-ecosystem: "deno"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      deno-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
